# Generated by Django 5.0 on 2024-08-30 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_emailverifylinksession_alter_accesslog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnFileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('public_id', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 277747))),
            ],
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 278671)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 253313)),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 275750)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 274929)),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 277369)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 278218)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 257521)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 276272)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 276293)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 254989)),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 254454)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 258105)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 273408)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 252094)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 257045)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 273869)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 253886)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 256430)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 252589)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 58, 26, 276718)),
        ),
    ]
