# Generated by Django 5.0 on 2024-09-02 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cdnfilemanager_alter_accesslog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnfilemanager',
            name='query_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 209601)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 166560)),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 205604)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 203795)),
        ),
        migrations.AlterField(
            model_name='cdnfilemanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 208638)),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 208234)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 209129)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 175809)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 206753)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 206798)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 170354)),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 169158)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 177145)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 200343)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 163677)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 174724)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 201404)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 167856)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 173383)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 164952)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 37, 29, 207532)),
        ),
    ]
