# Generated by Django 5.0 on 2024-09-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cdnfilemanager_query_id_alter_accesslog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 502494)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 476405)),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 499456)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 498603)),
        ),
        migrations.AlterField(
            model_name='cdnfilemanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 501524)),
        ),
        migrations.AlterField(
            model_name='countrycode',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='countrycode',
            name='iso_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 501122)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 502019)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 480803)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 499971)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 499998)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 478167)),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 477597)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 481421)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 497009)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 475150)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 480308)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 497504)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 477003)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 479664)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 475682)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 24, 38, 500449)),
        ),
    ]
