# Generated by Django 5.0 on 2024-09-02 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_accesslog_created_at_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 556284)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 530079)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='subadmin_register_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 553222)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 552366)),
        ),
        migrations.AlterField(
            model_name='cdnfilemanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 555320)),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 554916)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 555818)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 534463)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 553750)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 553769)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 531831)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='parking_owner_register_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='searchingslots_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 531270)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 535065)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 550778)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 528823)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 533973)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 551269)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 530678)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 533334)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 529346)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 21, 39, 31, 554227)),
        ),
    ]
