# Generated by Django 5.0 on 2024-09-07 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_accesslog_created_at_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingowner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_booking_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 312398)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 289707)),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 309999)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 309350)),
        ),
        migrations.AlterField(
            model_name='cdnfilemanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 311642)),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 311326)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 312025)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 293246)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 310412)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 310426)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 291090)),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 290659)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 293724)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 308116)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 288674)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 292841)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 308499)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 290188)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 292338)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 289137)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 20, 21, 310791)),
        ),
    ]
