# Generated by Django 5.0 on 2024-09-09 05:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_admin_is_verified_parkingowner_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='associate_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_admin_associate_admin', to='app.admin'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 865656)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 840669)),
        ),
        migrations.AlterField(
            model_name='adminchanginghistoryparkingareas',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 862706)),
        ),
        migrations.AlterField(
            model_name='arrivaldepart',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 861900)),
        ),
        migrations.AlterField(
            model_name='cdnfilemanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 864721)),
        ),
        migrations.AlterField(
            model_name='emailverifylinksession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 864325)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 865203)),
        ),
        migrations.AlterField(
            model_name='facilitychargesforarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 845224)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 863209)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 863226)),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 842419)),
        ),
        migrations.AlterField(
            model_name='parkingowner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 841893)),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 845816)),
        ),
        migrations.AlterField(
            model_name='parkingslotwithfacilities',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 860330)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 839472)),
        ),
        migrations.AlterField(
            model_name='slotfacility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 844704)),
        ),
        migrations.AlterField(
            model_name='slotunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 860801)),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 841280)),
        ),
        migrations.AlterField(
            model_name='subadminunderparkingarea',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 844070)),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 839974)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 10, 48, 5, 863661)),
        ),
    ]
